# Generated by Django 4.2 on 2024-07-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "Индивидуальный предприниматель")],
                        verbose_name="Уровень звена",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Задолженность перед поставщиком"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer",
                        to="network.networknode",
                    ),
                ),
            ],
            options={
                "verbose_name": "звено сети",
                "verbose_name_plural": "звенья сети",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("model", models.CharField(max_length=100, verbose_name="Модель")),
                ("on_market", models.DateField(verbose_name="Дата выхода на рынок")),
                (
                    "network_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="network.networknode",
                        verbose_name="Звено сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=100, verbose_name="Электронная почта")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("house_number", models.IntegerField(verbose_name="Номер дома")),
                (
                    "network_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="network.networknode",
                        verbose_name="Звено сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
    ]
